name: JAmmbazz A01 Core Kernel Builder

on:
  workflow_dispatch:
    inputs:
      kernel_url:
        description: 'Kernel kaynak kodu (Repo) URL adresi'
        required: true
        default: 'https://github.com/jammbazz/kernel-a01core-hw'
      kernel_branch:
        description: 'Branch adı'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Setup
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel bc python3 ccache zip libelf pahole cpio curl

      - name: Clone Kernel
        run: |
          git clone -b ${{ github.event.inputs.kernel_branch }} ${{ github.event.inputs.kernel_url }} kernel_src

      - name: Install RKSU
        working-directory: kernel_src
        run: |
          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -

      - name: Build
        working-directory: kernel_src
        run: |
          export ARCH=arm
          export KBUILD_BUILD_USER="jammbazz"
          export KBUILD_BUILD_HOST="GitHub-Actions"
          
          git clone https://github.com/Takumi123w/AnyKernel3.git AnyKernel3

          chmod +x ./arm-linux-androideabi-4.9/bin/* || true
          
          export CROSS_COMPILE=$(pwd)/arm-linux-androideabi-4.9/bin/arm-linux-androidkernel-
          export CC=$(pwd)/arm-linux-androideabi-4.9/bin/arm-linux-androidkernel-gcc
          
          mkdir -p out
          
          make O=out a01core_defconfig

          make O=out -j$(nproc --all) V=1 CONFIG_SECTION_MISMATCH_WARN_ONLY=y 2>&1

      - name: Package
        working-directory: kernel_src
        run: |
          TIME=$(date +%Y%m%d-%H%M)
          if [ -f "out/arch/arm/boot/Image" ]; then
            cp out/arch/arm/boot/Image ./AnyKernel3/Image
          else
            echo "HATA: Image bulunamadı!"
            exit 1
          fi
          
          cd AnyKernel3
          zip -r9 "../../Kernel-A01Core-Hawaii-KSU-$TIME.zip" * -x .git *.zip README.md *placeholder

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: A01Core-Hawaii-KSU-Kernel
          path: "*.zip"
